[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[functions]
  node_bundler = "esbuild"

[build.environment]
  PRISMA_QUERY_ENGINE_LIBRARY = "true"
